version: '3.8'

services:
  web:
    build: .
    container_name: car_service_web
    command: ./entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    restart: unless-stopped
