version: '3.8'

services:
  web:
    build: .
    container_name: car_service_web
    command: ./entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - SECRET_KEY=django-insecure-dev-key-change-in-production
      - SQL_DATABASE=car_service_db
      - SQL_USER=car_service_user
      - SQL_PASSWORD=dev_password_123
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    container_name: car_service_db
    image: postgres:17
    volumes:
      - ./container/pg_data/:/var/lib/postgresql/data/
      - ./container/pg_conf/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./container/pg_dump/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=car_service_db
      - POSTGRES_USER=car_service_user
      - POSTGRES_PASSWORD=dev_password_123
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U car_service_user -d car_service_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
