# Generated by Django 4.2.7 on 2025-09-09 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Име на клиент')),
                ('customer_address_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес 1')),
                ('customer_address_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес 2')),
                ('customer_mol', models.CharField(blank=True, max_length=255, null=True, verbose_name='МОЛ')),
                ('customer_taxno', models.CharField(blank=True, max_length=20, null=True, verbose_name='ДДС номер')),
                ('customer_doctype', models.SmallIntegerField(default=0, verbose_name='Тип документ')),
                ('receiver', models.CharField(blank=True, max_length=255, null=True, verbose_name='Получател')),
                ('receiver_details', models.CharField(blank=True, max_length=255, null=True, verbose_name='Детайли за получател')),
                ('customer_bulstat', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{9,11}$', 'БУЛСТАТ трябва да бъде 9-11 цифри')], verbose_name='БУЛСТАТ')),
                ('telno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('faxno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Факс')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Имейл')),
                ('res_address_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес за живеене 1')),
                ('res_address_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес за живеене 2')),
                ('eidate', models.DateTimeField(blank=True, null=True, verbose_name='Дата на влизане')),
                ('include', models.BooleanField(default=False, verbose_name='Включен')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('customer', models.BooleanField(default=True, verbose_name='Клиент')),
                ('supplier', models.BooleanField(default=False, verbose_name='Доставчик')),
                ('contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контакт')),
                ('partida', models.IntegerField(blank=True, null=True, verbose_name='Партида')),
                ('bulstatletter', models.CharField(blank=True, max_length=10, null=True, verbose_name='БУЛСТАТ буква')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Създаден на')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновен на')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенти',
                'ordering': ['customer_name'],
                'indexes': [models.Index(fields=['customer_name'], name='dashboard_c_custome_4fd8e0_idx'), models.Index(fields=['customer_taxno'], name='dashboard_c_custome_357123_idx'), models.Index(fields=['customer_bulstat'], name='dashboard_c_custome_2f4682_idx'), models.Index(fields=['active'], name='dashboard_c_active_ab066e_idx')],
            },
        ),
    ]
