# Generated by Django 4.2.7 on 2025-09-09 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_model', models.CharField(help_text='Например: FIAT DUCATO (250) 120 Multijet 2,3 D', max_length=255, verbose_name='Марка и модел')),
                ('vin', models.CharField(blank=True, help_text='Уникален номер на шасито', max_length=50, null=True, verbose_name='VIN/Шаси номер')),
                ('plate_number', models.CharField(blank=True, help_text='Например: CA1234AB', max_length=20, null=True, verbose_name='Регистрационен номер')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Година на производство')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвят')),
                ('engine_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер на двигател')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Създадена на')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновена на')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='dashboard.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Кола',
                'verbose_name_plural': 'Коли',
                'ordering': ['brand_model'],
                'indexes': [models.Index(fields=['brand_model'], name='dashboard_c_brand_m_74b79a_idx'), models.Index(fields=['vin'], name='dashboard_c_vin_1593f1_idx'), models.Index(fields=['plate_number'], name='dashboard_c_plate_n_583d61_idx'), models.Index(fields=['is_active'], name='dashboard_c_is_acti_b7f218_idx')],
                'unique_together': {('customer', 'vin')},
            },
        ),
    ]
