# Generated by Django 4.2.7 on 2025-09-09 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Име')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Имейл')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('employee_id', models.CharField(help_text='Уникален номер на служителя', max_length=20, unique=True, verbose_name='ID на служител')),
                ('position', models.CharField(blank=True, help_text='Например: Механик, Сервизен техник, Мениджър', max_length=100, null=True, verbose_name='Длъжност')),
                ('department', models.CharField(blank=True, help_text='Например: Сервиз, Администрация, Склад', max_length=100, null=True, verbose_name='Отдел')),
                ('monthly_working_hours', models.DecimalField(decimal_places=2, default=160.0, help_text='Стандартни месечни работни часове (по подразбиране 160)', max_digits=5, verbose_name='Месечни работни часове')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Почасова ставка в лева', max_digits=8, null=True, verbose_name='Почасова ставка')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата на назначаване')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Бележки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Създаден на')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновен на')),
            ],
            options={
                'verbose_name': 'Служител',
                'verbose_name_plural': 'Служители',
                'ordering': ['first_name', 'last_name'],
                'indexes': [models.Index(fields=['first_name', 'last_name'], name='dashboard_e_first_n_bd8bcb_idx'), models.Index(fields=['employee_id'], name='dashboard_e_employe_abe3cd_idx'), models.Index(fields=['is_active'], name='dashboard_e_is_acti_955352_idx'), models.Index(fields=['position'], name='dashboard_e_positio_bfba24_idx')],
            },
        ),
        migrations.CreateModel(
            name='DaysOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Начална дата')),
                ('end_date', models.DateField(verbose_name='Крайна дата')),
                ('day_off_type', models.CharField(choices=[('vacation', 'Годишен отпуск'), ('sick', 'Болничен'), ('personal', 'Лични причини'), ('holiday', 'Празник'), ('other', 'Друго')], default='vacation', max_length=20, verbose_name='Тип отпуск')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Причина')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Бележки')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрен')),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Одобрен от')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Одобрен на')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Създаден на')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновен на')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_off', to='dashboard.employee', verbose_name='Служител')),
            ],
            options={
                'verbose_name': 'Дни отпуск',
                'verbose_name_plural': 'Дни отпуск',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='dashboard_d_start_d_359192_idx'), models.Index(fields=['day_off_type'], name='dashboard_d_day_off_6f5089_idx'), models.Index(fields=['is_approved'], name='dashboard_d_is_appr_1162b1_idx')],
            },
        ),
    ]
