# Generated by Django 4.2.7 on 2025-09-09 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_employee_daysoff'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='dashboard_e_employe_abe3cd_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='dashboard_e_positio_bfba24_idx',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='monthly_working_hours',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
    ]
