# Generated by Django 4.2.7 on 2025-09-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_employee_dashboard_e_employe_abe3cd_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='annual_leave_days',
            field=models.IntegerField(default=20, help_text='Общо годишни отпускни дни (по подразбиране 20 за България)', verbose_name='Годишни отпускни дни'),
        ),
        migrations.AddField(
            model_name='employee',
            name='current_year_leave_used',
            field=models.IntegerField(default=0, verbose_name='Използвани отпускни дни за текущата година'),
        ),
    ]
