# Generated by Django 4.2.7 on 2025-09-09 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_employee_annual_leave_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заглавие')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('event_type', models.CharField(choices=[('meeting', 'Среща'), ('appointment', 'Записване'), ('maintenance', 'Поддръжка'), ('inspection', 'Преглед'), ('delivery', 'Доставка'), ('other', 'Друго')], default='meeting', max_length=20, verbose_name='Тип събитие')),
                ('start_datetime', models.DateTimeField(verbose_name='Начало')),
                ('end_datetime', models.DateTimeField(verbose_name='Край')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='Цял ден')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завършено')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Бележки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Създадено на')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновено на')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.customer', verbose_name='Клиент')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.employee', verbose_name='Служител')),
            ],
            options={
                'verbose_name': 'Събитие',
                'verbose_name_plural': 'Събития',
                'ordering': ['start_datetime'],
                'indexes': [models.Index(fields=['start_datetime', 'end_datetime'], name='dashboard_e_start_d_f310f3_idx'), models.Index(fields=['event_type'], name='dashboard_e_event_t_6352d9_idx'), models.Index(fields=['is_completed'], name='dashboard_e_is_comp_924060_idx')],
            },
        ),
    ]
