# Generated by Django 4.2.7 on 2025-09-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sklad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(help_text='Уникален номер на артикула', max_length=50, unique=True, verbose_name='Артикул N')),
                ('name', models.CharField(help_text='Име на продукта', max_length=255, verbose_name='Наименование')),
                ('unit', models.CharField(default='бр', help_text='Мерна единица (бр, кг, л, м, и т.н.)', max_length=20, verbose_name='Мр.')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Количество в наличност', max_digits=10, verbose_name='Наличност към')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Доставна цена за единица', max_digits=10, verbose_name='Дост. цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Създаден на')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновен на')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склад',
                'ordering': ['article_number'],
                'indexes': [models.Index(fields=['article_number'], name='dashboard_s_article_da02c0_idx'), models.Index(fields=['name'], name='dashboard_s_name_c3f491_idx'), models.Index(fields=['is_active'], name='dashboard_s_is_acti_869ad4_idx')],
            },
        ),
    ]
