# Generated by Django 4.2.7 on 2025-09-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_sklad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sklad',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Количество в наличност', max_digits=10, verbose_name='Наличност'),
        ),
    ]
