# Generated by Django 4.2.7 on 2025-09-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_sklad_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('starts94', 'Старс 94'), ('peugeot', 'Пежо'), ('nalichnosti', 'НАЛИЧНОСТИ')], max_length=20, verbose_name='Доставчик')),
                ('invoice_date', models.DateField(help_text='Дата от фактурата/документа', verbose_name='Дата на фактурата')),
                ('import_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата на импорт')),
                ('file_name', models.CharField(max_length=255, verbose_name='Име на файла')),
                ('items_created', models.PositiveIntegerField(default=0, verbose_name='Създадени артикули')),
                ('items_updated', models.PositiveIntegerField(default=0, verbose_name='Обновени артикули')),
                ('errors_count', models.PositiveIntegerField(default=0, verbose_name='Грешки')),
                ('total_processed', models.PositiveIntegerField(default=0, verbose_name='Общо обработени')),
                ('is_successful', models.BooleanField(default=True, verbose_name='Успешен импорт')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Съобщение за грешка')),
            ],
            options={
                'verbose_name': 'Импорт лог',
                'verbose_name_plural': 'Импорт логове',
                'ordering': ['-import_date'],
            },
        ),
    ]
