# Generated by Django 4.2.7 on 2025-09-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_importlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='importlog',
            name='skipped_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Пропуснати редове'),
        ),
    ]
