# Generated by Django 4.2.7 on 2025-09-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_importlog_skipped_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='importlog',
            name='affected_items',
            field=models.JSONField(blank=True, help_text='JSON с детайли за създадените и обновените артикули', null=True, verbose_name='Засегнати артикули'),
        ),
    ]
