# Generated by Django 4.2.7 on 2025-09-15 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_importlog_affected_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Уникален номер на поръчката', max_length=20, unique=True, verbose_name='Номер на поръчката')),
                ('order_date', models.DateField(help_text='Дата на създаване на поръчката', verbose_name='Дата на поръчката')),
                ('car_brand_model', models.CharField(blank=True, help_text='Например: C4 Picasso', max_length=255, null=True, verbose_name='Марка и модел')),
                ('car_vin', models.CharField(blank=True, help_text='Уникален номер на шасито', max_length=50, null=True, verbose_name='VIN/Шаси номер')),
                ('car_plate_number', models.CharField(blank=True, help_text='Например: СВ5602TK', max_length=20, null=True, verbose_name='Регистрационен номер')),
                ('car_mileage', models.PositiveIntegerField(blank=True, help_text='Текущ пробег на колата', null=True, verbose_name='Изминати км')),
                ('client_name', models.CharField(blank=True, help_text='Име на клиента', max_length=255, null=True, verbose_name='Име на клиента')),
                ('client_address', models.CharField(blank=True, help_text='Адрес на клиента', max_length=500, null=True, verbose_name='Адрес на клиента')),
                ('client_phone', models.CharField(blank=True, help_text='Телефонен номер на клиента', max_length=50, null=True, verbose_name='Телефон на клиента')),
                ('status', models.CharField(choices=[('pending', 'Чакаща'), ('in_progress', 'В процес'), ('completed', 'Завършена'), ('cancelled', 'Отказана')], default='pending', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, help_text='Допълнителни бележки за поръчката', null=True, verbose_name='Бележки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Създадена на')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновена на')),
                ('car', models.ForeignKey(blank=True, help_text='Изберете кола от базата данни', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.car', verbose_name='Кола')),
                ('client', models.ForeignKey(blank=True, help_text='Изберете клиент от базата данни', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.customer', verbose_name='Клиент')),
                ('employees', models.ManyToManyField(blank=True, help_text='Служители, които работят по тази поръчка', to='dashboard.employee', verbose_name='Служители')),
            ],
            options={
                'verbose_name': 'Поръчка',
                'verbose_name_plural': 'Поръчки',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(blank=True, help_text='Номер на артикула', max_length=50, null=True, verbose_name='Артикул номер')),
                ('name', models.CharField(help_text='Наименование на артикула или услугата', max_length=255, verbose_name='Наименование')),
                ('unit', models.CharField(help_text='бр, кг, л, м, норма, и т.н.', max_length=20, verbose_name='Мерна единица')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Цена за единица без ДДС', max_digits=10, verbose_name='Единична цена без ДДС')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Количество', max_digits=10, verbose_name='Количество')),
                ('is_labor', models.BooleanField(default=False, help_text='Отметнете ако това е труд/услуга', verbose_name='Труд')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Създаден на')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновен на')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='dashboard.order', verbose_name='Поръчка')),
                ('sklad_item', models.ForeignKey(blank=True, help_text='Изберете артикул от склад', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.sklad', verbose_name='Артикул от склад')),
            ],
            options={
                'verbose_name': 'Артикул от поръчка',
                'verbose_name_plural': 'Артикули от поръчка',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['order'], name='dashboard_o_order_i_d82e40_idx'), models.Index(fields=['is_labor'], name='dashboard_o_is_labo_4e8fd3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='dashboard_o_order_n_60b43e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_date'], name='dashboard_o_order_d_7ae001_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='dashboard_o_status_2e9809_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['car_vin'], name='dashboard_o_car_vin_e3e5bf_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['car_plate_number'], name='dashboard_o_car_pla_a50c1a_idx'),
        ),
    ]
