# Generated by Django 4.2.7 on 2025-09-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_order_orderitem_order_dashboard_o_order_n_60b43e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='include_vat',
            field=models.BooleanField(default=True, help_text='Отметнете ако артикулът трябва да включва ДДС', verbose_name='Включи ДДС'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('offer', 'Оферта'), ('invoice', 'Изготвена фактура')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
