# Generated by Django 4.2.7 on 2025-09-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_orderitem_include_vat_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='importlog',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Уникален номер на фактурата/документа', max_length=100, null=True, verbose_name='Номер на фактурата'),
        ),
        migrations.AddField(
            model_name='importlog',
            name='import_identifier',
            field=models.CharField(blank=True, help_text='Уникален идентификатор за предотвратяване на дублиране', max_length=200, null=True, unique=True, verbose_name='Идентификатор на импорта'),
        ),
    ]
