# Generated by Django 4.2.7 on 2025-09-24 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20250924_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Уникален номер на фактурата', max_length=50, unique=True, verbose_name='Номер на фактура')),
                ('invoice_date', models.DateField(help_text='Дата на издаване на фактурата', verbose_name='Дата на фактура')),
                ('due_date', models.DateField(help_text='Дата до която трябва да бъде платена фактурата', verbose_name='Краен срок за плащане')),
                ('client_name', models.CharField(help_text='Име на клиента', max_length=255, verbose_name='Име на клиент')),
                ('client_address', models.TextField(blank=True, help_text='Адрес на клиента', verbose_name='Адрес на клиент')),
                ('client_phone', models.CharField(blank=True, help_text='Телефонен номер на клиента', max_length=20, verbose_name='Телефон на клиент')),
                ('client_tax_number', models.CharField(blank=True, help_text='ДДС номер на клиента', max_length=50, verbose_name='ДДС номер на клиент')),
                ('car_brand_model', models.CharField(blank=True, help_text='Марка и модел на автомобила', max_length=255, verbose_name='Марка и модел на кола')),
                ('car_plate_number', models.CharField(blank=True, help_text='Регистрационен номер на автомобила', max_length=20, verbose_name='Регистрационен номер')),
                ('car_vin', models.CharField(blank=True, help_text='VIN номер на автомобила', max_length=17, verbose_name='VIN номер')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Сума преди ДДС', max_digits=10, verbose_name='Междинна сума')),
                ('vat_amount', models.DecimalField(decimal_places=2, help_text='Сума на ДДС', max_digits=10, verbose_name='ДДС сума')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Обща сума с ДДС', max_digits=10, verbose_name='Обща сума')),
                ('status', models.CharField(choices=[('draft', 'Чернова'), ('sent', 'Изпратена'), ('paid', 'Платена'), ('overdue', 'Просрочена'), ('cancelled', 'Отказана')], default='draft', help_text='Статус на фактурата', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, help_text='Допълнителни бележки за фактурата', verbose_name='Бележки')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и час на създаване', verbose_name='Създадена на')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и час на последно обновяване', verbose_name='Обновена на')),
                ('order', models.OneToOneField(help_text='Поръчката, от която е създадена фактурата', on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='dashboard.order', verbose_name='Свързана поръчка')),
            ],
            options={
                'verbose_name': 'Фактура',
                'verbose_name_plural': 'Фактури',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
    ]
