# Generated by Django 4.2.7 on 2025-09-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('sent', 'Изпратена'), ('paid', 'Платена'), ('overdue', 'Просрочена'), ('cancelled', 'Отказана')], default='sent', help_text='Статус на фактурата', max_length=20, verbose_name='Статус'),
        ),
    ]
