# Generated by Django 4.2.7 on 2025-09-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_update_invoice_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_with_vat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена за единица с ДДС', max_digits=10, null=True, verbose_name='Единична цена с ДДС'),
        ),
    ]
