# Generated by Django 4.2.7 on 2025-09-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_add_price_with_vat_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('offer', 'Оферта'), ('invoice', 'Изготвена фактура'), ('order', 'Изготвена поръчка')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
