# Generated by Django 4.2.7 on 2025-09-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_add_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='current_mileage',
            field=models.PositiveIntegerField(blank=True, help_text='Последен записан пробег на колата', null=True, verbose_name='Текущ пробег'),
        ),
    ]
