# Generated by Django 4.2.7 on 2025-09-30 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_add_temp_id_to_customer'),
        ('dashboard', '0019_add_current_mileage_to_car'),
    ]

    operations = [
    ]
