# Generated by Django 4.2.7 on 2025-09-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_merge_20250930_1715'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='dashboard_customer_temp_id_idx',
        ),
        migrations.AlterField(
            model_name='customer',
            name='temp_id',
            field=models.IntegerField(blank=True, help_text='Оригинален Customer-ID от старата система за мапинг на поръчки', null=True, unique=True, verbose_name='Временен ID'),
        ),
    ]
